apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: textile-app

type: Opaque

stringData:
  MONGO_URL: "mongodb+srv://sunysudeep:1EHx5mSYSyAbYGUg@cluster0.ckgnm3d.mongodb.net/?appName=Cluster0" 