name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Backend Image
        run: |
          docker build \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:latest \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:$IMAGE_TAG \
          ./backend

      - name: Push Backend Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:latest

          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:$IMAGE_TAG
  
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Frontend Image
        run: |
          docker build \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:latest \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:$IMAGE_TAG \
          ./frontend

      - name: Push Frontend Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:$IMAGE_TAG


# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:

#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v2

#       - name: Set Image Tag
#         run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

#       - name: Build Backend Image
#         run: |
#           docker build \
#           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:latest \
#           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:$IMAGE_TAG \
#           ./backend

#       - name: Push Backend Image
#         run: |
#           docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:latest

#           docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-backend:$IMAGE_TAG
          

#       - name: Build Frontend Image
#         run: |
#           docker build \
#           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:latest \
#           -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:$IMAGE_TAG \
#           ./frontend

#       - name: Push Frontend Image
#         run: |
#           docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:latest
#           docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/textile-frontend:$IMAGE_TAG
